### ISSUE TITLE
CMake Error cv_bridgeConfig.cmake:113

### ISSUE THREAD

**Issue by HamadRemeithi** [ros-perception/vision_opencv#503] opened 2022-12-02 09:21 UTC
Created a fresh install of ROS Melodic on Ubuntu 18.04 following instructions from:
http://wiki.ros.org/melodic/Installation/Ubuntu

Also was going through instruction in the the next repo to run the provided simulation:
https://github.com/VIS4ROB-lab/ccm_slam

Faced an issue at section 3.2 in the repo when executing the command:
`catkin build ccmslam --cmake-args -DG2O_U14=0 -DCMAKE_BUILD_TYPE=Release`

Error faced:
```
CMake Error at /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake:113 (message):
  Project 'cv_bridge' specifies '/usr/include/opencv' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '${{prefix}}//usr/include/opencv'.  Check the issue tracker
  'https://github.com/ros-perception/vision_opencv/issues' and consider
  creating a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:66 (find_package)
```

**Comment by ijnek** [comment] 2022-12-03 01:25
Closing, as this is a duplicate of #345.Please refer to the thread for some work arounds.

**Closed as not planned by ijnek** 2022-12-03 01:25 UTC
