### ISSUE TITLE
ROS Noetic std::bad_alloc

### ISSUE THREAD

**Issue by martin-91x** [ros-perception/vision_opencv#408] opened 2021-09-21 14:28 UTC
Hi,

I'm currently trying to get one of my rosnodes running with noetic (built from source) on Ubuntu 18.04.
Building the cv_bridge package workers just fine, and so does building my rosnode.

Here some log when building the cv_bridge:
```shell
-- Using CATKIN_DEVEL_PREFIX: /home/nvidia/ros_catkin_ws/devel_isolated/cv_bridge
-- Using CMAKE_PREFIX_PATH: /home/nvidia/ros_catkin_ws/install_isolated
-- This workspace overlays: /home/nvidia/ros_catkin_ws/install_isolated
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/nvidia/ros_catkin_ws/build_isolated/cv_bridge/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so (found version "3.6.9")
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.6")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/ros_catkin_ws/build_isolated/cv_bridge
```

However, when I try to run my node, I get the following error:
```Converting image...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

The corresponding lines of code are quite simple:
```C++
        void img_cb(const sensor_msgs::Image::ConstPtr &img_msg) { 
            // Callback function for image_subscriber
           ...
                // Convert image message to opencv image
                debug_print("Converting image...\n"); 
                cv_bridge::CvImagePtr cv_ptr = cv_bridge::toCvCopy(img_msg, sensor_msgs::image_encodings::BGR8);
                debug_print("Done!");
                if(!cv_ptr->image.empty()){
                   ....
```

**Comment by ijnek** [comment] 2022-09-12 01:37
There doesn't seem to be enough information here to identify a problem. Considering this issue is from a year ago, I'm going to close this off. If you still have the same problem, please post on [ROS Answers](https://answers.ros.org/questions/) including more details. Once you identify what the problem is, please create a new issue against the repo.

Also - I'd recommend using gdb for ``std::bad_alloc`` error.

**Closed as not planned by ijnek** 2022-09-12 01:37 UTC
Labels: noetic
