### ISSUE TITLE
cv_bridge does not support endianness

### ISSUE THREAD

**Issue by vrabaud** [ros-perception/vision_opencv#7] opened 2013-01-10 15:22 UTC
Original bug report by @jack-oquin

I am trying to add the mono16 IIDC 1394 modes back in for Diamondback. They did not work in Cturtle,  https://code.ros.org/trac/ros-pkg/ticket/4142 fixed a crash, but did not make those modes work.

The image_view node still does not display the images correctly. The IIDC specification requires hardware images to provide multi-byte pixels in big endian format. I do not think swapping the bytes in the driver is a good solution.

If we are not going to support the is_bigendian field in the Image message, we should remove it and document the fact that all multi-byte data must be little-endian (or is that "whatever byte orientation is supported by the system the driver runs on").

**Comment by vrabaud** [comment] 2015-11-16 22:09
@jack-oquin, would you please have a rosbag with such data so that I can work on that bug ? Thx.

**Comment by jack-oquin** [comment] 2015-11-18 20:59
This problem was opened years ago. I do not believe I currently have access to any device that can generates mono16 images. I must have had some data back then that would demonstrate the error, because I do remember seeing it. 

So no, I can't provide a rosbag with such an image. 

That's too bad, because I'm pretty sure it was a genuine problem back then. But, nobody that I am aware of has complained about it since, so there must not be many devices producing those kinds of images. Maybe it's been fixed due to some other OpenCV update.

I recommend closing this issue as not reproducible, at least until someone can provide a test case.

**Comment by vrabaud** [comment] 2015-11-18 21:15
oh, this is trivial to fix and has nothing to do with OpenCV. It needs to be fixed here:
https://github.com/ros-perception/vision_opencv/blob/indigo/cv_bridge/src/cv_bridge.cpp#L264
A pointer to the data in the image is always given to OpenCV but it is always stored in little endian, as https://github.com/ros-perception/vision_opencv/blob/indigo/cv_bridge/src/cv_bridge.cpp#L336 indicates.

Now problem is simple: what does big endian mean in the stream case ? Let's say the ROS image is big endian and its data contains:

```
00 01 10 11
```

(those are bytes made of 2 bits for the sake of the example).
Should this be converted by keeping the byte order but reverting the bits

```
00 10 01 11
```

by keeping the bit order but reverting the bytes:

```
11 10 01 00
```

by reverting the bit or byte order:

```
11 01 10 00
```

It seems it's only the bit ordering but I am just ignorant  ... If you have a good pointer :)

**Comment by jack-oquin** [comment] 2015-11-20 14:53
Good question. My interpretation is this:

```
01 00 11 10
```

In [old Unix jargon](http://betterexplained.com/articles/understanding-big-and-little-endian-byte-order/): what you get when storing the four-byte ASCII sequence for "UNIX" as a `long int` on a big-endian machine would become "NUXI" or "XINU" on a little-endian box, since the byte reversal occurs on 16-bit (e.g. PDP-11) or 32-bit (e.g. VAX) boundaries. As I understand it, each `mono16` pixel contains two consecutive bytes (so "NUXI" in this case), and the byte order of the image much be converted to the byte order of the host system. 

Normally communications code would use `ntohs()` to convert from network byte order to that of the host machine. But "network" byte order is always assumed to be big-endian in the Internet world. In this case, the "image" byte order depends on the device firmware, which could be either. So, the correct action depends on whether the host byte order is the same or different from the image byte order. If they differ, then swap the two bytes. 

That is my interpretation of the `is_bigendian` field in [sensor_msgs/Image](http://docs.ros.org/api/sensor_msgs/html/msg/Image.html): if it differs from the host, we need to swap. What I probably saw before was `is_bigendian` being ignored in the message with the image byte order assumed to be the same as the host. All this also depends on the camera driver setting `is_bigendian` correctly, of course, which may not be happening if the field has previously been ignored.

This is sufficiently complicated that I'd like to solicit comments on ros-sig-drivers.

**Comment by jack-oquin** [comment] 2015-11-20 14:58
Note that the IIDC standard for 1394 cameras specifies that the device should always send the data big-endian. So, for those cameras, "image" order is the standard Unix "network" order.

**Comment by jack-oquin** [comment] 2015-11-20 16:16
Vincent: I just checked some specifications, and I _do_ have [a 1394 camera that supports mono16 modes](https://pro.sony.com/bbsc/ssr/product-XCDSX90CR/). When viewed on an Intel architecture machine, it should exhibit this problem. 

It'll take some time to attach it to my current development machine, but will demonstrate whether this is still a problem: image_view will display mostly snow, but with a vague outline of the scene. If it's still broken, I'll collect a bag that you can use for testing.

**Closed as completed** 2015-11-22 21:38 UTC

**Comment by vrabaud** [comment] 2015-11-22 21:39
ok, I think we finally got this one, but if you have a bag, I'd still love to add it to the tests.
And btw, your convention for endianness for stream is totally right, I just had to look over the internet ... Thx a bunch !!!
